name: Alertas Discord
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "DEVOPS PUC PR - VICTOR DE GODOY PAESE - SOMATIVA 2 !"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
